services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_BACK_URL_DEV: ${VITE_BACK_URL_DEV}
        VITE_MODE: ${VITE_MODE}
    ports:
      - "3001:80"
      # - "host:container"
    env_file:
      - .env
