import { Model } from "sequelize";

export enum TokenEventType {
  ACCESS = "ACCESS",
  REFRESH = "REFRESH",
  VERIFY_ACCOUNT = "VERIFY_ACCOUNT",
  FORGOT_PWD = "FORGOT_PWD",
  CHANGE_PWD = "CHANGE_PWD",
  CHANGE_EMAIL = "CHANGE_EMAIL",
}

export enum MsgHMAC {
  NOT_FOUND = "VERIFY_TOKEN_NOT_FOUND",
  NOT_EMITTED = "VERIFY_TOKEN_NOT_EMITTED",
  EXPIRED = "VERIFY_TOKEN_EXPIRED",
  OK = "OK",
}
