export enum ErrAppMsgCode {
  ACCESS_EXPIRED = "ACCESS TOKEN EXPIRED",
  ACCESS_INVALID = "ACCESS_TOKEN_INVALID",
  ACCESS_NOT_PROVIDED = "ACCESS TOKEN NOT PROVIDED",

  REFRESH_EXPIRED = "REFRESH TOKEN EXPIRED",
  REFRESH_INVALID = "REFRESH TOKEN INVALID",
  REFRESH_NOT_PROVIDED = "REFRESH TOKEN NOT PROVIDED",
}

export const isAccessExpired = (msg: string) =>
  [
    ErrAppMsgCode.ACCESS_EXPIRED,
    ErrAppMsgCode.ACCESS_INVALID,
    ErrAppMsgCode.ACCESS_NOT_PROVIDED,
  ].includes(msg as ErrAppMsgCode);
