export enum ErrAppMsgCode {
  ACCESS_EXPIRED = "ACCESS TOKEN EXPIRED",
  ACCESS_INVALID = "ACCESS_TOKEN_INVALID",
  ACCESS_NOT_PROVIDED = "ACCESS TOKEN NOT PROVIDED",

  REFRESH_EXPIRED = "REFRESH TOKEN EXPIRED",
  REFRESH_INVALID = "REFRESH TOKEN INVALID",
  REFRESH_NOT_PROVIDED = "REFRESH TOKEN NOT PROVIDED",
}

export enum EventApp {
  OK = "SUCCESS",
  ERR = "ERROR",
  INFO = "INFO",
}

export enum AllowedFromNotice {
  REGISTER = "/auth/register",
  VERIFY_ACCOUNT = "/auth/verify-account",
  FORGOT_PWD = "/auth/forgot-pwd",
}
