export enum MsgErrSession {
  ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID = "ACCESS_TOKEN_INVALID",
  ACCESS_TOKEN_NOT_PROVIDED = "ACCESS_TOKEN_NOT_PROVIDED",

  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_NOT_PROVIDED = "REFRESH_TOKEN_NOT_PROVIDED",
}

export enum EventApp {
  OK = "SUCCESS",
  ERR = "ERROR",
  INFO = "INFO",
}

export enum TokenEventType {
  VERIFY_ACCOUNT = "VERIFY_ACCOUNT",
  FORGOT_PWD = "FORGOT_PWD",
  CHANGE_PWD = "CHANGE_PWD",
  CHANGE_EMAIL = "CHANGE_EMAIL",
}

export enum AllowedFromNotice {
  REGISTER = "/auth/register",
  FORGOT_PWD = "/auth/forgot-pwd",
  VERIFY_ACCOUNT = "/auth/verify-cb",
}

export enum TagsAPI {
  USER = "USER",
}
