export enum MsgErrAccess {
  ACCESS_EXPIRED = "ACCESS_EXPIRED",
  ACCESS_INVALID = "ACCESS_INVALID",
  ACCESS_NOT_PROVIDED = "ACCESS_NOT_PROVIDED",
}

export enum MsgErrRefresh {
  REFRESH_NOT_EMITTED = "REFRESH_NOT_EMITTED ",
  REFRESH_EXPIRED = "REFRESH_EXPIRED ",
  REFRESH_INVALID = "REFRESH_INVALID ",
  REFRESH_NOT_PROVIDED = "REFRESH_NOT_PROVIDED ",
}

export enum TokenEventType {
  VERIFY_ACCOUNT = "VERIFY_ACCOUNT",
  FORGOT_PWD = "FORGOT_PWD",
  CHANGE_EMAIL = "CHANGE_EMAIL",
  SECURITY = "SECURITY",
  // VERIFY_ACCOUNT = "ed29cfcac10efcbb5a76b139f8226d6",
  // FORGOT_PWD = "4f60a8f192560fa55764ac9ed3d5faf9",
  // CHANGE_EMAIL = "9086aa36957000093a3d72ab100004b0",
  // SECURITY = "f48100f806d741e8b7daf3a206a6ba24",
}

export enum EndpointClearTokenOnErr {
  FORGOT_PWD = "/auth/recover-account",
  CHANGE_EMAIL = "/user/update-email",
  RESET_PWD = "/user/reset-pwd",
}

export enum MsgCheckToken {
  NOT_FOUND = "VERIFY_TOKEN_NOT_FOUND",
  NOT_EMITTED = "VERIFY_TOKEN_NOT_EMITTED",
  NOT_PROVIDED = "VERIFY_TOKEN_NOT_PROVIDED",
  INVALID = "VERIFY_TOKEN_INVALID",
  EXPIRED = "VERIFY_TOKEN_EXPIRED",
}
